name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  build-android-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - uses: AndreaMolinari/rn-conventional-release@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
